name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les commits de main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: ng build --configuration=production --base-href "/vchaillo/"

      - name: Force https
        run: touch dist/vchaillo/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Branche où le site sera déployé
          folder: dist/vchaillo  # Dossier de sortie Angular (remplace vchaillo par ton nom de projet)
